# Generated by Django 5.1.6 on 2025-04-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
