# Generated by Django 5.1.6 on 2026-03-18 11:47

import django.db.models.deletion
from django.db import migrations, models


def copy_coach_team_to_team_coach(apps, schema_editor):
    Team = apps.get_model('main', 'Team')
    Coach = apps.get_model('main', 'Coach')

    # 0006 state has Coach.team (FK), 0007 introduces Team.coach (FK).
    # Keep one coach per team in this intermediate schema (lowest coach id).
    for team in Team.objects.all():
        coach_id = (
            Coach.objects
            .filter(team_id=team.id)
            .order_by('id')
            .values_list('id', flat=True)
            .first()
        )
        if coach_id:
            team.coach_id = coach_id
            team.save(update_fields=['coach'])


def copy_team_coach_to_coach_team(apps, schema_editor):
    Team = apps.get_model('main', 'Team')
    Coach = apps.get_model('main', 'Coach')

    for team in Team.objects.exclude(coach_id__isnull=True):
        Coach.objects.filter(id=team.coach_id).update(team_id=team.id)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_coach_team_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coach'),
        ),
        migrations.RunPython(copy_coach_team_to_team_coach, copy_team_coach_to_coach_team),
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
    ]
