# Generated by Django 5.1.6 on 2026-03-18 11:55

import django.db.models.deletion
from django.db import migrations, models


def copy_team_coach_to_coach_team(apps, schema_editor):
    Team = apps.get_model('main', 'Team')
    Coach = apps.get_model('main', 'Coach')

    for team in Team.objects.exclude(coach_id__isnull=True):
        Coach.objects.filter(id=team.coach_id).update(team_id=team.id)


def copy_coach_team_to_team_coach(apps, schema_editor):
    Team = apps.get_model('main', 'Team')
    Coach = apps.get_model('main', 'Coach')

    for team in Team.objects.all():
        coach_id = (
            Coach.objects
            .filter(team_id=team.id)
            .order_by('id')
            .values_list('id', flat=True)
            .first()
        )
        if coach_id:
            team.coach_id = coach_id
            team.save(update_fields=['coach'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_coach_team_team_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='main.team'),
        ),
        migrations.RunPython(copy_team_coach_to_coach_team, copy_coach_team_to_team_coach),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
    ]
